# Generated by Django 5.0.4 on 2024-05-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_remaining_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='remaining_place',
        ),
        migrations.AddField(
            model_name='event',
            name='sold_place',
            field=models.IntegerField(default=0),
        ),
    ]
