# Generated by Django 5.0.4 on 2024-05-24 07:10

import event.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_flyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='flyers',
            field=models.ImageField(blank=True, upload_to=event.models.user_directory_path),
        ),
    ]
