# Generated by Django 5.0.4 on 2024-05-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_event_price_alter_event_flyers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='revenus',
            field=models.FloatField(default=0),
        ),
    ]
