# Generated by Django 5.0.4 on 2024-06-08 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_user_profil'),
        ('event', '0008_event_revenus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Authentication.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.CharField(default='', max_length=20),
        ),
    ]
