# Generated by Django 5.0.4 on 2024-06-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_remove_event_revenus_event_adresse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='adresse',
            new_name='adress',
        ),
        migrations.AddField(
            model_name='event',
            name='revenus',
            field=models.FloatField(default=0),
        ),
    ]
