# Generated by Django 5.0.4 on 2024-06-11 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_rename_adresse_event_adress_event_revenus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
    ]
