# Generated by Django 5.0.4 on 2024-06-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_remove_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
