# Generated by Django 5.0.4 on 2024-05-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profil',
            field=models.ImageField(null=True, upload_to='uploads/User.username'),
        ),
    ]
